# Generated by Django 4.2.5 on 2023-09-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='giftTo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
